name: Manual Approval Step

on:
  workflow_call:

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for manual approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: ItsAlvii
          minimum-approvals: 1

