name: Manual Approval

on:
  workflow_call:

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Await manual approval
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          approvers: your-github-username
          minimum-approvals: 1
          issue-title: "Approve Production Deployment"
          issue-body: "Approve to deploy to Production?"

