name: Deploy to Staging

on:
  workflow_call:

jobs:
  deploy-stage:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging Server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_STAGE_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pipeline-backend:latest
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/pipeline-frontend:latest
            docker stop backend frontend || true
            docker rm backend frontend || true
            docker run -d --name backend -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/pipeline-backend:latest
            docker run -d --name frontend -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/pipeline-frontend:latest

