name: Build Phase

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pipeline-backend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pipeline-backend:latest

      - name: Build and push frontend image
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/pipeline-frontend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/pipeline-frontend:latest

