name: Deploy Phase

on:
  workflow_call:
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      SSH_PRIVATE_KEY:
        required: true
      SSH_USER:
        required: true
      EC2_STAGE_HOST:
        required: true
      EC2_PROD_HOST:
        required: true

jobs:
  stage:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Staging via SSH
        uses: appleboy/ssh-action@v1.8.0
        with:
          host: ${{ secrets.EC2_STAGE_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest || true
            docker rm -f backend frontend || true
            docker network create app-network 2>/dev/null || true
            docker run -d --name backend --network app-network ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
            docker run -d --name frontend --network app-network -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

  approval:
    needs: stage
    runs-on: ubuntu-latest
    steps:
      - name: Manual approval (pause)
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.token }}
          minimum-approvals: 1

  prod:
    needs: approval
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production via SSH
        uses: appleboy/ssh-action@v1.8.0
        with:
          host: ${{ secrets.EC2_PROD_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest || true
            docker rm -f backend frontend || true
            docker network create app-network 2>/dev/null || true
            docker run -d --name backend --network app-network ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
            docker run -d --name frontend --network app-network -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest

