name: Deploy Phase

on:
  workflow_call:
    secrets:
      SSH_PRIVATE_KEY:
        required: true
      SSH_USER:
        required: true
      EC2_STAGE_HOST:
        required: true
      EC2_PROD_HOST:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_STAGE_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2 (Stage)
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.EC2_STAGE_HOST }} "docker pull myapp:latest && docker run -d myapp:latest"

      - name: Deploy to EC2 (Prod)
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.EC2_PROD_HOST }} "docker pull myapp:latest && docker run -d myapp:latest"

