name: CI/CD Pipeline (orchestra)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_phase:
    uses: ./.github/workflows/build.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  test_phase:
    needs: build_phase
    uses: ./.github/workflows/test.yml
    secrets:
      SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
      TRIVY_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy_phase:
    needs: test_phase
    uses: ./.github/workflows/deploy.yml
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_USER: ${{ secrets.SSH_USER }}
      EC2_STAGE_HOST: ${{ secrets.EC2_STAGE_HOST }}
      EC2_PROD_HOST: ${{ secrets.EC2_PROD_HOST }}

