name: CI/CD Pipeline (orchestra)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  sonar:
    needs: build
    uses: ./.github/workflows/test-sonar.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  trivy:
    needs: sonar
    uses: ./.github/workflows/test-trivy.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

  deploy-stage:
    needs: trivy
    uses: ./.github/workflows/deploy-stage.yml
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_USER: ${{ secrets.SSH_USER }}
      EC2_STAGE_HOST: ${{ secrets.EC2_STAGE_HOST }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

  approval:
    needs: deploy-stage
    uses: ./.github/workflows/deploy-approval.yml

  deploy-prod:
    needs: approval
    uses: ./.github/workflows/deploy-prod.yml
    secrets:
      SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      SSH_USER: ${{ secrets.SSH_USER }}
      EC2_PROD_HOST: ${{ secrets.EC2_PROD_HOST }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

