name: CI/CD Pipeline (orchestra)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build/build.yml

  sonar:
    needs: build
    uses: ./.github/workflows/test/sonar.yml

  trivy:
    needs: sonar
    uses: ./.github/workflows/test/trivy.yml

  deploy-stage:
    needs: trivy
    uses: ./.github/workflows/deploy/stage.yml

  approval:
    needs: deploy-stage
    uses: ./.github/workflows/deploy/approval.yml

  deploy-prod:
    needs: approval
    uses: ./.github/workflows/deploy/prod.yml

